### ISSUE TITLE
Support for concatenated commands

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#25]
Numerous instrument support to receive several commands separated by a special character (';' most of the time). It would be nice to support that feature. (I often use it in instrument with channel when the channel selection must be done before hand using a special command, by concatenating both channel selection command and the actual command I can always be sure that the right channel is selected).

**Comment by hgrecco** [comment]
I agree. We should add this!

**Comment by MatthieuDartiailh** [comment]
As it is quite straightforward I will probably do it in my work on channels. I hope to have a PR ready by the end of the week.

**Comment by hgrecco** [comment]
great

**Comment by MatthieuDartiailh** [comment]
This was closed by #27.
