### ISSUE TITLE
Add support for error queue

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#26]
Some instrument write errors to an error queue which can be queried using a special command. I would need this for some instruments. Any idea @hgrecco about how to make error handling flexible enough to allow and say that a command need to hook into a device function ?

**Comment by hgrecco** [comment]
Have you look at #13. It goes in that direction, but is not a queue. I am sure it can be extended.

**Comment by hgrecco** [comment]
Closing thanks to #28 
If another aspect is pending, please open another issue.
