### ISSUE TITLE
Add support for TCPIP SOCKET instrument

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#29]
I will need that for some instrument (Attocube driver for lantz). Could you please indicate me the procedure to follow ? Can I simply duplicate the the TCPIP INSTR implementation or should I be wary of some points ?

**Comment by hgrecco** [comment]
Yes. Just copy TCPIP INSTR and change after_parsing. Other attributes are handled in `sessions.Session`.

**Comment by MatthieuDartiailh** [comment]
Done in #30
