### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#3]
You suggested discussing features and implementation. Here seems to be a good place to start.

**Comment by hgrecco** [comment]
I opening issues for the individual parts to simplify tracking the implementation changes. Advancing with this will help us to get rid of lantz simulators.

**Comment by MatthieuDartiailh** [comment]
Sounds good !

**Comment by hgrecco** [comment]
Implemented using YAML,
