### ISSUE TITLE
Add support for query in list_resources.

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#36]
Once again this is necessary for Lantz testing.

**Comment by hgrecco** [comment]
Actually I have this partially implemented in pyvisa-py. My plan is to move it to `VisaLibraryBase` (in pyvisa) to allow other backend to use it or overwrite if necessary (in the same as we are doing it with `parse_resource`.  We can then continue improving the support for more complicated queries.

**Comment by MatthieuDartiailh** [comment]
Good to know. I beed this to properly test the via_usb methods.

**Comment by hgrecco** [comment]
Done!. There is a function in `pyvisa.rname` called `filter` that implements the filtering. It is still very basic, but will do the trick to start. We can then implement the other parts of the VISA expr language.

You need the latest develop of PyVISA for this. As soon as we test it a little bit more, I will push a new PyVISA, PyVISA-py and PyVISA-sim release.

**Comment by MatthieuDartiailh** [comment]
I should be able to add the tests to Lantz the first week of august. I will keep you posted.
